### ISSUE TITLE
Crashes when /Users/user/Library/Safari/Databases is non existant

### ISSUE THREAD

**Issue by SchumacherFM** [jipegit/OSXAuditor#23]
```
[INFO] user's Safari databases
Traceback (most recent call last):
  File "osxauditor.py", line 1702, in <module>
    Main()
  File "osxauditor.py", line 1663, in Main
    ParseBrowsers()
  File "osxauditor.py", line 808, in ParseBrowsers
    ParseSafari()
  File "osxauditor.py", line 745, in ParseSafari
    ParseSafariProfile(User, UserSafariProfilePath)
  File "osxauditor.py", line 723, in ParseSafariProfile
    for Db in os.listdir(os.path.join(Path, "Databases")):
OSError: [Errno 2] No such file or directory: '/Users/user/Library/Safari/Databases'
```

**Comment by ArnaudLoos** [comment]
I'm having a very similar issue with relation to the Guest account and a missing Safari plist. Disabling the Guest account does not fix it.

[INFO] The plist does not have a dictionary as its root as expected: /Users/Guest/Library/Safari/LastSession.plist
Traceback (most recent call last):
  File "osxauditor.py", line 1702, in <module>
    Main()
  File "osxauditor.py", line 1663, in Main
    ParseBrowsers()
  File "osxauditor.py", line 808, in ParseBrowsers
    ParseSafari()
  File "osxauditor.py", line 745, in ParseSafari
    ParseSafariProfile(User, UserSafariProfilePath)
  File "osxauditor.py", line 716, in ParseSafariProfile
    if "SessionWindows" in LastSessionPlist:
TypeError: argument of type 'NoneType' is not iterable

**Comment by jipegit** [comment]
Fixed.
