### ISSUE TITLE
Traceback when checking Safari's LastSession

### ISSUE THREAD

**Issue by ssabetan** [jipegit/OSXAuditor#28]
```
[INFO] sam's Safari LastSession
[INFO] /Users/sam/Library/Safari/LastSession.plist
Traceback (most recent call last):
  File "osxauditor.py", line 1702, in <module>
    Main()
  File "osxauditor.py", line 1663, in Main
    ParseBrowsers()
  File "osxauditor.py", line 808, in ParseBrowsers
    ParseSafari()
  File "osxauditor.py", line 745, in ParseSafari
    ParseSafariProfile(User, UserSafariProfilePath)
  File "osxauditor.py", line 717, in ParseSafariProfile
    LastSession = LastSessionPlist["SessionWindows"][0]["TabStates"][0]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 451, in __getitem__objectAtIndex_
    return container_unwrap(self.objectAtIndex_(idx), RuntimeError)
IndexError: NSRangeException - -[__NSCFArray objectAtIndex:]: index (0) beyond bounds (0)
```

Python Version:

```
2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)]
```

I'm running on a Mac with Mountain Lion 10.9.4. Any ideas?

**Comment by jipegit** [comment]
Should be fixed.
