### ISSUE TITLE
Unable to parse "com.apple.loginitems.plist"

### ISSUE THREAD

**Issue by sligodave** [jipegit/OSXAuditor#30]
When I run with:
```sudo python osxauditor.py -a -m -l localhashes.db -H log.html```
I get the following error:
```
[INFO] Users' LoginItems
[INFO] sligodave's LoginItems
[INFO] /Users/sligodave/Library/Preferences/com.apple.loginitems.plist
[INFO] Cannot parse /Users/sligodave/Library/Preferences/com.apple.loginitems.plist (Binary or JSON plist may FAIL)

Traceback (most recent call last):
  File "osxauditor.py", line 1702, in <module>
    Main()
  File "osxauditor.py", line 1651, in Main
    ParseStartup()
  File "osxauditor.py", line 550, in ParseStartup
    if "SessionItems" in LoginItemsPlist:
TypeError: argument of type 'bool' is not iterable
```
Also, the log.html is empty, so I'm afraid I can't help with anything from that.

**Comment by jipegit** [comment]
Fixed.
