### ISSUE TITLE
Crash no output report log.html generated

### ISSUE THREAD

**Issue by VGraupera** [jipegit/OSXAuditor#31]
Ran with 

```
sudo python osxauditor.py -a -m -l localhashes.db -H log.html
```

runs for a while but does produce report. log.html. log is empty. Here is the crash

```
[INFO] Error with /Users/macadmin/Library/Application Support/Google/Chrome/Default/Web Data: ("Could not decode to UTF-8 column 'value' with text '^\xb4|\xc6W\x81\xc42UW\xe5\xc2\x9e\xfbj\xdd\xff\xfcE\x9f\xd3\xf2q\x10\xf2\x90\xa1DT\x9b\x94\xe0'",)
[INFO] macadmin's Chrome databases
Traceback (most recent call last):
  File "osxauditor.py", line 1702, in <module>
    Main()
  File "osxauditor.py", line 1663, in Main
    ParseBrowsers()
  File "osxauditor.py", line 810, in ParseBrowsers
    ParseChrome()
  File "osxauditor.py", line 801, in ParseChrome
    ParseChromeProfile(User, UsersChromePath)
  File "osxauditor.py", line 773, in ParseChromeProfile
    for Db in os.listdir(os.path.join(Path, "databases")):
OSError: [Errno 2] No such file or directory: '/Users/macadmin/Library/Application Support/Google/Chrome/Default/databases'
```
then it exits

**Comment by jipegit** [comment]
Can't reproduce.
