### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by ccorcos** [jipegit/OSXAuditor#33]
An interesting error.

```
Traceback (most recent call last):
  File "osxauditor.py", line 1702, in <module>
    Main()
  File "osxauditor.py", line 1657, in Main
    ParseQuarantines()
  File "osxauditor.py", line 440, in ParseQuarantines
    JointLSQuarantineEvent += u";" + unicode(Q)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 48: ordinal not in range(128)
```

**Comment by muqiuq** [comment]
I got the same error. Is this going to be fixed?

**Comment by jipegit** [comment]
Should be fixed.

**Comment by jipegit** [comment]
Duplicate of #27
