### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'OC_PythonLong' objects

### ISSUE THREAD

**Issue by ccorcos** [jipegit/OSXAuditor#35]
```[INFO] Email accounts
Traceback (most recent call last):
  File "osxauditor.py", line 1705, in <module>
    Main()
  File "osxauditor.py", line 1675, in Main
    ParseUsersAccounts()
  File "osxauditor.py", line 1188, in ParseUsersAccounts
    ParseMailAppAccount(MailAccountPlistPath)
  File "osxauditor.py", line 1009, in ParseMailAppAccount
    if "PortNumber" in MailAccount: MAccountPref += "(" + MailAccount["PortNumber"]  + ") - "
TypeError: cannot concatenate 'str' and 'OC_PythonLong' objects```

Dang. This program has been running for 2 hours, then I get this error. :/

I've had three errors so far trying to run this script -- it seems that some try-except blocks would be a great way to make this code more robust to errors like this...

**Comment by sts** [comment]
:+1

**Comment by zx8** [comment]
+1

**Comment by nafarkash** [comment]
any solution for this problem?

**Comment by jesusjjf** [comment]
+1 having same issue. 
any updates?

**Comment by jipegit** [comment]
Fixed, thanks.
