### ISSUE TITLE
PortNumber errors

### ISSUE THREAD

**Issue by mindprince** [jipegit/OSXAuditor#37]
When I ran `sudo python osxauditor.py -qsidAUe -l localhashes.db -H log.html`, I got
```
Traceback (most recent call last):
  File "osxauditor.py", line 1702, in <module>
    Main()
  File "osxauditor.py", line 1672, in Main
    ParseUsersAccounts()
  File "osxauditor.py", line 1185, in ParseUsersAccounts
    ParseMailAppAccount(MailAccountPlistPath)
  File "osxauditor.py", line 1006, in ParseMailAppAccount
    if "PortNumber" in MailAccount: MAccountPref += "(" + MailAccount["PortNumber"]  + ") - "
TypeError: cannot concatenate 'str' and 'OC_PythonLong' objects
```

After I fixed the above error, I got this:
```
Traceback (most recent call last):
  File "osxauditor.py", line 1702, in <module>
    Main()
  File "osxauditor.py", line 1672, in Main
    ParseUsersAccounts()
  File "osxauditor.py", line 1185, in ParseUsersAccounts
    ParseMailAppAccount(MailAccountPlistPath)
  File "osxauditor.py", line 1027, in ParseMailAppAccount
    if "PortNumber" in DeliveryAccount: DAccountPref += "(" + MailAccount["PortNumber"]  + ") - "
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 188, in __getitem__objectForKey_
    return container_unwrap(res, KeyError, key)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 654, in container_unwrap
    raise exc_type(*exc_args)
KeyError: 'PortNumber'
```

**Comment by kennysmoothx** [comment]
+1

```
[INFO] /Users/Kenneth/Library/Containers/com.apple.mail/Data/Library/Mail/V2/MailData/Accounts.plist
[INFO] Email accounts
Traceback (most recent call last):
  File "osxauditor.py", line 1702, in <module>
    Main()
  File "osxauditor.py", line 1672, in Main
    ParseUsersAccounts()
  File "osxauditor.py", line 1185, in ParseUsersAccounts
    ParseMailAppAccount(MailAccountPlistPath)
  File "osxauditor.py", line 1006, in ParseMailAppAccount
    if "PortNumber" in MailAccount: MAccountPref += "(" + MailAccount["PortNumber"]  + ") - "
TypeError: cannot concatenate 'str' and 'OC_PythonLong' objects
```

**Comment by jesusjjf** [comment]
+1
any updates on this issue?

**Comment by jipegit** [comment]
Fixed, thanks.
