### ISSUE TITLE
KeyError: LastConnected

### ISSUE THREAD

**Issue by drewcrawford** [jipegit/OSXAuditor#44]
```
sudo python osxauditor.py -a > audit.txt
Traceback (most recent call last):
  File "osxauditor.py", line 1684, in <module>
    Main()
  File "osxauditor.py", line 1657, in Main
    ParseAirportPrefs()
  File "osxauditor.py", line 946, in ParseAirportPrefs
    PrintAndLog(u'SSID: ' + KnownNetworks[KnownNetwork]['SSIDString'].decode('utf-8') + u' - SSID: ' + str(KnownNetworks[KnownNetwork]['SSID']) + u' - Last connected: ' + str(KnownNetworks[KnownNetwork]['LastConnected']) + u' - Security type: ' + KnownNetworks[KnownNetwork]['SecurityType'] + u' - Geolocation: ' + Geolocation, 'INFO')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 162, in __getitem__objectForKey_
    return container_unwrap(res, KeyError, key)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 659, in container_unwrap
    raise exc_type(*exc_args)
KeyError: 'LastConnected'
```

**Comment by jipegit** [comment]
Fixed.
