### ISSUE TITLE
Traceback when checking SMTP email's port

### ISSUE THREAD

**Issue by davidep** [jipegit/OSXAuditor#45]
```
DEBUG: Mac OS X Obj-C Foundation successfully imported
[INFO] Report generated by OS X Auditor v0.4.4 on ...
[INFO] Audited system path: /
[INFO] Version of the audited system: Mac OS X 10.8.5 build 12F2560
.
.
.
[INFO] SMTP accounts
Traceback (most recent call last):
  File "osxauditor.py", line 1693, in <module>
    Main()
  File "osxauditor.py", line 1669, in Main
    ParseUsersAccounts()
  File "osxauditor.py", line 1166, in ParseUsersAccounts
    ParseMailAppAccount(MailAccountPlistPath)
  File "osxauditor.py", line 1005, in ParseMailAppAccount
    if 'PortNumber' in DeliveryAccount: DAccountPref += '(' + str(MailAccount['PortNumber'])  + ') - '
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 168, in __getitem__objectForKey_
    return container_unwrap(res, KeyError, key)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 634, in container_unwrap
    raise exc_type(*exc_args)
KeyError: 'PortNumber'
```

**Comment by jipegit** [comment]
Should be fixed by #46
