### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by rogerlucas** [jipegit/OSXAuditor#50]
[INFO] /Users/xxxx/Library/Preferences/com.apple.loginitems.plist
App Tamer.apSSDApplications/App Tamer.app/
Traceback (most recent call last):
  File "osxauditor.py", line 1697, in <module>
    Main()
  File "osxauditor.py", line 1652, in Main
    ParseStartup()
  File "osxauditor.py", line 531, in ParseStartup
    PrintAndLog(CustomListItem['Name'].decode('utf-8') + u' - ' + binascii.hexlify(CustomListItem['Alias']).decode('hex').decode('utf-8', 'ignore'), 'INFO')
  File "osxauditor.py", line 227, in PrintAndLog
    print(u'[INFO] ' + LogStr)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u04b3' in position 41: ordinal not in range(128)

**Comment by rogerlucas** [comment]
I temporarily added a try: except: to give bypass it and be able to test.
